version: '3.4'

services:

  unicornstore:
    image: "164382793440.dkr.ecr.us-east-1.amazonaws.com/modernization-unicorn-store"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - UNICORNSTORE_DBSECRET={"username":"awssa","password":"BBTh123ca","engine":"sqlserver","host":"mujvotr2kczjaj.cmunybjnipxj.us-east-1.rds.amazonaws.com","port":1433,"dbInstanceIdentifier":"mujvotr2kczjaj"}
      - DefaultAdminUsername=Administrator@test.com
      - DefaultAdminPassword=Secret1*